name: Update dynamic badge

on:
  push:
    branches:
      - main
      - dev

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Update Gist badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: b88f2ddeecdf6bd04647dce99bfcf0bc
          filename: infinity-status.json
          label: status
          message: ${{ github.ref_name == 'main' && 'production ready' || 'status developing' }}
          color: ${{ github.ref_name == 'main' && 'blue' || 'orange' }}